[workspace]
members = [
    "program/flash-arbitrage",
]
resolver = "2"

[workspace.dependencies]
anchor-lang = { version = "0.29.0", features = ["init-if-needed"] }
anchor-spl = "0.29.0"
solana-program = "1.17.2"