[package]
name = "flash_arbitrage"
version = "0.1.0"
edition = "2021"
description = "Solana Flash Loan Arbitrage Program"

[dependencies]
anchor-lang = { workspace = true }
anchor-spl = { workspace = true }
solana-program = { workspace = true }